name: Build Docker Images

on:
  push:
    branches:
      - master
  
  watch:
    types: [started]

jobs:
  dockerhub:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version
        id: get_version
        run: echo "X_UI_VERSION=$(curl -s https://api.github.com/repos/vaxilu/x-ui/releases/latest | grep tag_name | awk '{print $2}' | sed 's/[",]//g')" >> $GITHUB_OUTPUT          

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            X_UI_VERSION=${{ steps.get_version.outputs.X_UI_VERSION }}
          context: .            
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/x-ui:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/x-ui:latest
          cache-from: type=registry,ref=${{ github.repository }}:cache
          cache-to: type=registry,ref=${{ github.repository }}:cache,mode=max         